# Generated by Django 3.2.9 on 2022-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAboutSounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=2, verbose_name='звук')),
                ('description', models.TextField(verbose_name='опис вимови')),
                ('image', models.ImageField(upload_to='', verbose_name='ілюстрація вимови')),
            ],
        ),
    ]
