# Generated by Django 3.2.9 on 2022-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutsounds',
            name='row',
            field=models.TextField(default='', verbose_name='ряд'),
        ),
        migrations.AlterField(
            model_name='informationaboutsounds',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='ілюстрація вимови'),
        ),
        migrations.AlterField(
            model_name='informationaboutsounds',
            name='sound',
            field=models.CharField(max_length=5, verbose_name='звук'),
        ),
    ]
