# Generated by Django 3.2.13 on 2022-05-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220520_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutsounds',
            name='documents',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='informationaboutsounds',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
