# Generated by Django 3.2.13 on 2022-06-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220609_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationaboutconsonants',
            name='sound',
            field=models.CharField(max_length=6, verbose_name='звук'),
        ),
    ]
