# Generated by Django 3.2.14 on 2022-08-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_informationaboutconsonants_sound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationaboutconsonants',
            old_name='documents',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='informationaboutvowels',
            old_name='documents',
            new_name='audio',
        ),
    ]
