# Generated by Django 3.2.14 on 2024-05-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220801_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutconsonants',
            name='eng_description',
            field=models.TextField(default='', verbose_name='англ. опис вимови'),
        ),
        migrations.AddField(
            model_name='informationaboutvowels',
            name='eng_description',
            field=models.TextField(default='', verbose_name='англ. опис вимови'),
        ),
    ]
