# Generated by Django 3.2.14 on 2024-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240510_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutconsonants',
            name='male_audio',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='informationaboutvowels',
            name='male_audio',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
