# Generated by Django 3.2.14 on 2024-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240512_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(default='', verbose_name='text')),
                ('audio', models.FileField(default='', upload_to='documents/')),
            ],
        ),
    ]
