# Generated by Django 3.2.14 on 2024-05-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='text',
            new_name='sound',
        ),
    ]
